// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DocAside: typeof import('./components/DocAside.vue')['default']
    DocAsideItem: typeof import('./components/DocAsideItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Nav: typeof import('./components/Header/Nav.vue')['default']
    Post: typeof import('./components/Post/index.vue')['default']
    PostContent: typeof import('./components/Post/PostContent.vue')['default']
    PostHeading: typeof import('./components/Post/PostHeading.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
